/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss_fase2.presentation;

import dss_fase2.business.Cidadao;
import dss_fase2.business.Eleicao;

/**
 *
 * @author filipeoliveira
 */
public class MainWindow extends javax.swing.JFrame {
    private Cidadao cidadaoActivo;
    private Eleicao eleicao;
    
    /**
     * Creates new form janelaLogin
     */
    
    private void enablePanel( String panel) {
        this.painel_admin_apresentar_resultado.setVisible(false);
                this.painel_admin_encerrar_votacao.setVisible(false);
                        this.painel_admin_iniciar_votacao.setVisible(false);
                                this.painel_eleitor_votar.setVisible(false);
                                        this.painel_eleitor_votar_antecipadamente.setVisible(false);
                                                this.painel_sistema_login.setVisible(false);
                                                        this.painel_sistema_logout.setVisible(false);
           
        switch(panel){
            case "login": 
                                                                this.painel_sistema_login.setVisible(true);
                                                                        this.setContentPane(painel_sistema_login);
                break;
            case "logout": 
                break;
            case "votar": 
                break;
             case "votar_antecipadamente": 
                break;
             case "iniciar_votacao": 
                break;
             case "encerrar_votacao": 
                break;
             case "apresentar_resultados": 
                break;
                                    
                
        }
    }
    
    public MainWindow() {
        initComponents();
        
        //menu sistema
        this.menuSistema.setVisible(true);
        this.painel_sistema_login.setVisible(true);
        this.painel_sistema_logout.setVisible(false);
        
        //menu eleitor
       // this.menuEleitor.setVisible(false);
        this.painel_eleitor_votar.setVisible(false);
        this.painel_eleitor_votar_antecipadamente.setVisible(false);
        
        //menu admin
        //this.menuAdmin.setVisible(false);
        this.painel_admin_apresentar_resultado.setVisible(false);
        this.painel_admin_encerrar_votacao.setVisible(false);
        this.painel_admin_iniciar_votacao.setVisible(false);


        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_admin_iniciar_votacao = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        painel_eleitor_votar_antecipadamente = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        painel_sistema_login = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        painel_admin_encerrar_votacao = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        painel_eleitor_votar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        painel_admin_apresentar_resultado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painel_sistema_logout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuSistema = new javax.swing.JMenu();
        item_login = new javax.swing.JMenuItem();
        item_logout = new javax.swing.JMenuItem();
        menuEleitor = new javax.swing.JMenu();
        item_votar = new javax.swing.JMenuItem();
        item_votar_antecipadamente = new javax.swing.JMenuItem();
        menuAdmin = new javax.swing.JMenu();
        item_iniciar_votacao = new javax.swing.JMenuItem();
        item_encerrar_votacao = new javax.swing.JMenuItem();
        item_apresentar_resultado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame_principal");

        painel_admin_iniciar_votacao.setEnabled(false);

        jLabel7.setText("iniciar votação");

        javax.swing.GroupLayout painel_admin_iniciar_votacaoLayout = new javax.swing.GroupLayout(painel_admin_iniciar_votacao);
        painel_admin_iniciar_votacao.setLayout(painel_admin_iniciar_votacaoLayout);
        painel_admin_iniciar_votacaoLayout.setHorizontalGroup(
            painel_admin_iniciar_votacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_admin_iniciar_votacaoLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(123, 123, 123))
        );
        painel_admin_iniciar_votacaoLayout.setVerticalGroup(
            painel_admin_iniciar_votacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_admin_iniciar_votacaoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addContainerGap(1181, Short.MAX_VALUE))
        );

        painel_eleitor_votar_antecipadamente.setEnabled(false);

        jLabel6.setText("votar antecipadamente");

        javax.swing.GroupLayout painel_eleitor_votar_antecipadamenteLayout = new javax.swing.GroupLayout(painel_eleitor_votar_antecipadamente);
        painel_eleitor_votar_antecipadamente.setLayout(painel_eleitor_votar_antecipadamenteLayout);
        painel_eleitor_votar_antecipadamenteLayout.setHorizontalGroup(
            painel_eleitor_votar_antecipadamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_eleitor_votar_antecipadamenteLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(123, 123, 123))
        );
        painel_eleitor_votar_antecipadamenteLayout.setVerticalGroup(
            painel_eleitor_votar_antecipadamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_eleitor_votar_antecipadamenteLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel6)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jLabel5.setText("login");

        javax.swing.GroupLayout painel_sistema_loginLayout = new javax.swing.GroupLayout(painel_sistema_login);
        painel_sistema_login.setLayout(painel_sistema_loginLayout);
        painel_sistema_loginLayout.setHorizontalGroup(
            painel_sistema_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_sistema_loginLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel5)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        painel_sistema_loginLayout.setVerticalGroup(
            painel_sistema_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_sistema_loginLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel5)
                .addContainerGap(1078, Short.MAX_VALUE))
        );

        painel_admin_encerrar_votacao.setEnabled(false);

        jLabel4.setText("encerrar votacao");

        javax.swing.GroupLayout painel_admin_encerrar_votacaoLayout = new javax.swing.GroupLayout(painel_admin_encerrar_votacao);
        painel_admin_encerrar_votacao.setLayout(painel_admin_encerrar_votacaoLayout);
        painel_admin_encerrar_votacaoLayout.setHorizontalGroup(
            painel_admin_encerrar_votacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_admin_encerrar_votacaoLayout.createSequentialGroup()
                .addGap(512, 512, 512)
                .addComponent(jLabel4)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        painel_admin_encerrar_votacaoLayout.setVerticalGroup(
            painel_admin_encerrar_votacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_admin_encerrar_votacaoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        painel_eleitor_votar.setEnabled(false);

        jLabel2.setText("votar");

        javax.swing.GroupLayout painel_eleitor_votarLayout = new javax.swing.GroupLayout(painel_eleitor_votar);
        painel_eleitor_votar.setLayout(painel_eleitor_votarLayout);
        painel_eleitor_votarLayout.setHorizontalGroup(
            painel_eleitor_votarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_eleitor_votarLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel2)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        painel_eleitor_votarLayout.setVerticalGroup(
            painel_eleitor_votarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_eleitor_votarLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        painel_admin_apresentar_resultado.setEnabled(false);

        jLabel1.setText("apresentar resultado");

        javax.swing.GroupLayout painel_admin_apresentar_resultadoLayout = new javax.swing.GroupLayout(painel_admin_apresentar_resultado);
        painel_admin_apresentar_resultado.setLayout(painel_admin_apresentar_resultadoLayout);
        painel_admin_apresentar_resultadoLayout.setHorizontalGroup(
            painel_admin_apresentar_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_admin_apresentar_resultadoLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel1)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        painel_admin_apresentar_resultadoLayout.setVerticalGroup(
            painel_admin_apresentar_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_admin_apresentar_resultadoLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        painel_sistema_logout.setEnabled(false);
        painel_sistema_logout.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel3.setText("logout");

        javax.swing.GroupLayout painel_sistema_logoutLayout = new javax.swing.GroupLayout(painel_sistema_logout);
        painel_sistema_logout.setLayout(painel_sistema_logoutLayout);
        painel_sistema_logoutLayout.setHorizontalGroup(
            painel_sistema_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_sistema_logoutLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel3)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        painel_sistema_logoutLayout.setVerticalGroup(
            painel_sistema_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_sistema_logoutLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel3)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        menuSistema.setText("Sistema");

        item_login.setText("login");
        item_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_loginActionPerformed(evt);
            }
        });
        menuSistema.add(item_login);

        item_logout.setText("logout");
        item_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_logoutActionPerformed(evt);
            }
        });
        menuSistema.add(item_logout);

        menuBar.add(menuSistema);

        menuEleitor.setText("Eleitor");

        item_votar.setText("votara");
        item_votar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_votarActionPerformed(evt);
            }
        });
        menuEleitor.add(item_votar);

        item_votar_antecipadamente.setText("votar antecipadamente");
        item_votar_antecipadamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_votar_antecipadamenteActionPerformed(evt);
            }
        });
        menuEleitor.add(item_votar_antecipadamente);

        menuBar.add(menuEleitor);

        menuAdmin.setText("Admin");

        item_iniciar_votacao.setText("iniciar votação");
        item_iniciar_votacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_iniciar_votacaoActionPerformed(evt);
            }
        });
        menuAdmin.add(item_iniciar_votacao);

        item_encerrar_votacao.setText("encerrar votação");
        item_encerrar_votacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_encerrar_votacaoActionPerformed(evt);
            }
        });
        menuAdmin.add(item_encerrar_votacao);

        item_apresentar_resultado.setText("apresentar resultado");
        item_apresentar_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_apresentar_resultadoActionPerformed(evt);
            }
        });
        menuAdmin.add(item_apresentar_resultado);

        menuBar.add(menuAdmin);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_sistema_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(painel_admin_encerrar_votacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painel_admin_iniciar_votacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painel_eleitor_votar_antecipadamente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painel_sistema_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painel_eleitor_votar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(662, 662, 662)
                    .addComponent(painel_admin_apresentar_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(663, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(painel_admin_encerrar_votacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(636, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_sistema_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painel_admin_iniciar_votacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painel_eleitor_votar_antecipadamente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painel_sistema_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painel_eleitor_votar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(424, 424, 424)
                    .addComponent(painel_admin_apresentar_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(431, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_votarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_votarActionPerformed
        
        
        this.setContentPane(painel_eleitor_votar);
    }//GEN-LAST:event_item_votarActionPerformed

    private void item_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_logoutActionPerformed
        this.setContentPane(painel_sistema_logout);
        
    }//GEN-LAST:event_item_logoutActionPerformed

    private void item_votar_antecipadamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_votar_antecipadamenteActionPerformed
        this.setContentPane(painel_eleitor_votar_antecipadamente);
    }//GEN-LAST:event_item_votar_antecipadamenteActionPerformed

    private void item_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_loginActionPerformed
        this.setContentPane(painel_sistema_login);
    }//GEN-LAST:event_item_loginActionPerformed

    private void item_iniciar_votacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_iniciar_votacaoActionPerformed
        this.setContentPane(painel_admin_iniciar_votacao);
    }//GEN-LAST:event_item_iniciar_votacaoActionPerformed

    private void item_encerrar_votacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_encerrar_votacaoActionPerformed
        this.setContentPane(painel_admin_encerrar_votacao);
    }//GEN-LAST:event_item_encerrar_votacaoActionPerformed

    private void item_apresentar_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_apresentar_resultadoActionPerformed
                this.setContentPane(painel_admin_apresentar_resultado);
    }//GEN-LAST:event_item_apresentar_resultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem item_apresentar_resultado;
    private javax.swing.JMenuItem item_encerrar_votacao;
    private javax.swing.JMenuItem item_iniciar_votacao;
    private javax.swing.JMenuItem item_login;
    private javax.swing.JMenuItem item_logout;
    private javax.swing.JMenuItem item_votar;
    private javax.swing.JMenuItem item_votar_antecipadamente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEleitor;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JPanel painel_admin_apresentar_resultado;
    private javax.swing.JPanel painel_admin_encerrar_votacao;
    private javax.swing.JPanel painel_admin_iniciar_votacao;
    private javax.swing.JPanel painel_eleitor_votar;
    private javax.swing.JPanel painel_eleitor_votar_antecipadamente;
    private javax.swing.JPanel painel_sistema_login;
    private javax.swing.JPanel painel_sistema_logout;
    // End of variables declaration//GEN-END:variables
}
