/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss_fase2.presentation;

import dss_fase2.business.Cidadao;
import dss_fase2.business.Eleicao;

/**
 *
 * @author filipeoliveira
 */
public class MainWindow extends javax.swing.JFrame {
  private Cidadao cidadaoActivo;
  private Eleicao eleicao;

  /**
   * Creates new form janelaLogin
   */

  private void loadElectionData(){
      this.eleicao = new Eleicao();
      this.eleicao.populateDataFromDB("localhost","dss","dss_USER", "123");
  }
  
  private void enablePanel( String panel) {
    this.painel_admin_apresentar_resultado.setVisible(false);
    this.painel_admin_encerrar_votacao.setVisible(false);
    this.painel_admin_iniciar_votacao.setVisible(false);
    this.painel_eleitor_votar.setVisible(false);
    this.painel_eleitor_votar_antecipadamente.setVisible(false);
    this.painel_sistema_login.setVisible(false);
    this.painel_sistema_logout.setVisible(false);

    switch(panel){
      case "login": 
        this.painel_sistema_login.setVisible(true);
        this.setContentPane(painel_sistema_login);
        break;
      case "logout":
        this.painel_sistema_logout.setVisible(true);
        this.setContentPane(painel_sistema_logout);
        break;
      case "votar": 
        this.painel_eleitor_votar.setVisible(true);
        this.setContentPane(painel_eleitor_votar);
        break;
      case "votar_antecipadamente":
        this.painel_eleitor_votar_antecipadamente.setVisible(true);
        this.setContentPane(painel_eleitor_votar_antecipadamente);
        break;
      case "iniciar_votacao":
        this.painel_admin_iniciar_votacao.setVisible(true);
        this.setContentPane(painel_admin_iniciar_votacao);
        break;
      case "encerrar_votacao":
        this.painel_admin_encerrar_votacao.setVisible(true);
        this.setContentPane(painel_admin_encerrar_votacao);
        break;
      case "apresentar_resultado":
        this.painel_admin_apresentar_resultado.setVisible(true);
        this.setContentPane(painel_admin_apresentar_resultado);
        break;
    }
  }

  public MainWindow() {
    initComponents();

    //menu sistema
    this.menuSistema.setVisible(true);

    //menu eleitor
    this.menuEleitor.setVisible(false);
    
    //menu admin
    this.menuAdmin.setVisible(false);
    
    enablePanel("login");



  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_sistema_logout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        painel_admin_encerrar_votacao = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        painel_admin_apresentar_resultado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painel_admin_iniciar_votacao = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        painel_eleitor_votar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        painel_eleitor_votar_antecipadamente = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        painel_sistema_login = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        field_cc = new javax.swing.JTextField();
        field_password = new javax.swing.JTextField();
        butao_login = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuSistema = new javax.swing.JMenu();
        item_login = new javax.swing.JMenuItem();
        item_logout = new javax.swing.JMenuItem();
        menuEleitor = new javax.swing.JMenu();
        item_votar = new javax.swing.JMenuItem();
        item_votar_antecipadamente = new javax.swing.JMenuItem();
        menuAdmin = new javax.swing.JMenu();
        item_iniciar_votacao = new javax.swing.JMenuItem();
        item_encerrar_votacao = new javax.swing.JMenuItem();
        item_apresentar_resultado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame_principal");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        painel_sistema_logout.setEnabled(false);
        painel_sistema_logout.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel3.setText("logout");

        javax.swing.GroupLayout painel_sistema_logoutLayout = new javax.swing.GroupLayout(painel_sistema_logout);
        painel_sistema_logout.setLayout(painel_sistema_logoutLayout);
        painel_sistema_logoutLayout.setHorizontalGroup(
            painel_sistema_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_sistema_logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(453, Short.MAX_VALUE))
        );
        painel_sistema_logoutLayout.setVerticalGroup(
            painel_sistema_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_sistema_logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        painel_admin_encerrar_votacao.setEnabled(false);
        painel_admin_encerrar_votacao.setPreferredSize(new java.awt.Dimension(500, 500));
        painel_admin_encerrar_votacao.setSize(new java.awt.Dimension(500, 500));

        jLabel4.setText("encerrar votacao");

        javax.swing.GroupLayout painel_admin_encerrar_votacaoLayout = new javax.swing.GroupLayout(painel_admin_encerrar_votacao);
        painel_admin_encerrar_votacao.setLayout(painel_admin_encerrar_votacaoLayout);
        painel_admin_encerrar_votacaoLayout.setHorizontalGroup(
            painel_admin_encerrar_votacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_admin_encerrar_votacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(390, Short.MAX_VALUE))
        );
        painel_admin_encerrar_votacaoLayout.setVerticalGroup(
            painel_admin_encerrar_votacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_admin_encerrar_votacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        painel_admin_apresentar_resultado.setEnabled(false);
        painel_admin_apresentar_resultado.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setText("apresentar resultado");

        javax.swing.GroupLayout painel_admin_apresentar_resultadoLayout = new javax.swing.GroupLayout(painel_admin_apresentar_resultado);
        painel_admin_apresentar_resultado.setLayout(painel_admin_apresentar_resultadoLayout);
        painel_admin_apresentar_resultadoLayout.setHorizontalGroup(
            painel_admin_apresentar_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_admin_apresentar_resultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        painel_admin_apresentar_resultadoLayout.setVerticalGroup(
            painel_admin_apresentar_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_admin_apresentar_resultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(492, Short.MAX_VALUE))
        );

        painel_admin_iniciar_votacao.setEnabled(false);
        painel_admin_iniciar_votacao.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel7.setText("iniciar votação");

        javax.swing.GroupLayout painel_admin_iniciar_votacaoLayout = new javax.swing.GroupLayout(painel_admin_iniciar_votacao);
        painel_admin_iniciar_votacao.setLayout(painel_admin_iniciar_votacaoLayout);
        painel_admin_iniciar_votacaoLayout.setHorizontalGroup(
            painel_admin_iniciar_votacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_admin_iniciar_votacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        painel_admin_iniciar_votacaoLayout.setVerticalGroup(
            painel_admin_iniciar_votacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_admin_iniciar_votacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        painel_eleitor_votar.setEnabled(false);
        painel_eleitor_votar.setPreferredSize(new java.awt.Dimension(500, 500));
        painel_eleitor_votar.setSize(new java.awt.Dimension(500, 500));

        jLabel2.setText("votar");

        javax.swing.GroupLayout painel_eleitor_votarLayout = new javax.swing.GroupLayout(painel_eleitor_votar);
        painel_eleitor_votar.setLayout(painel_eleitor_votarLayout);
        painel_eleitor_votarLayout.setHorizontalGroup(
            painel_eleitor_votarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_eleitor_votarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        painel_eleitor_votarLayout.setVerticalGroup(
            painel_eleitor_votarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_eleitor_votarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        painel_eleitor_votar_antecipadamente.setEnabled(false);
        painel_eleitor_votar_antecipadamente.setPreferredSize(new java.awt.Dimension(500, 500));
        painel_eleitor_votar_antecipadamente.setSize(new java.awt.Dimension(500, 500));

        jLabel6.setText("votar antecipadamente");

        javax.swing.GroupLayout painel_eleitor_votar_antecipadamenteLayout = new javax.swing.GroupLayout(painel_eleitor_votar_antecipadamente);
        painel_eleitor_votar_antecipadamente.setLayout(painel_eleitor_votar_antecipadamenteLayout);
        painel_eleitor_votar_antecipadamenteLayout.setHorizontalGroup(
            painel_eleitor_votar_antecipadamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_eleitor_votar_antecipadamenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        painel_eleitor_votar_antecipadamenteLayout.setVerticalGroup(
            painel_eleitor_votar_antecipadamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_eleitor_votar_antecipadamenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        painel_sistema_login.setPreferredSize(new java.awt.Dimension(500, 500));
        painel_sistema_login.setSize(new java.awt.Dimension(500, 500));

        jLabel5.setText("login");

        jLabel8.setText("Cartão Cidadão");

        jLabel9.setText("Password");

        field_cc.setToolTipText("");
        field_cc.setMinimumSize(new java.awt.Dimension(160, 28));
        field_cc.setPreferredSize(new java.awt.Dimension(160, 28));
        field_cc.setSize(new java.awt.Dimension(160, 28));
        field_cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_ccActionPerformed(evt);
            }
        });

        field_password.setPreferredSize(new java.awt.Dimension(160, 28));
        field_password.setSize(new java.awt.Dimension(160, 28));

        butao_login.setLabel("Login");
        butao_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_sistema_loginLayout = new javax.swing.GroupLayout(painel_sistema_login);
        painel_sistema_login.setLayout(painel_sistema_loginLayout);
        painel_sistema_loginLayout.setHorizontalGroup(
            painel_sistema_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_sistema_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_sistema_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(painel_sistema_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(butao_login)
                        .addGroup(painel_sistema_loginLayout.createSequentialGroup()
                            .addGroup(painel_sistema_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(painel_sistema_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(field_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(field_cc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        painel_sistema_loginLayout.setVerticalGroup(
            painel_sistema_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_sistema_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(painel_sistema_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(field_cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_sistema_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(field_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butao_login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuSistema.setText("Sistema");

        item_login.setText("login");
        item_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_loginActionPerformed(evt);
            }
        });
        menuSistema.add(item_login);

        item_logout.setText("logout");
        item_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_logoutActionPerformed(evt);
            }
        });
        menuSistema.add(item_logout);

        menuBar.add(menuSistema);

        menuEleitor.setText("Eleitor");

        item_votar.setText("votar");
        item_votar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_votarActionPerformed(evt);
            }
        });
        menuEleitor.add(item_votar);

        item_votar_antecipadamente.setText("votar antecipadamente");
        item_votar_antecipadamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_votar_antecipadamenteActionPerformed(evt);
            }
        });
        menuEleitor.add(item_votar_antecipadamente);

        menuBar.add(menuEleitor);

        menuAdmin.setText("Admin");

        item_iniciar_votacao.setText("iniciar votação");
        item_iniciar_votacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_iniciar_votacaoActionPerformed(evt);
            }
        });
        menuAdmin.add(item_iniciar_votacao);

        item_encerrar_votacao.setText("encerrar votação");
        item_encerrar_votacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_encerrar_votacaoActionPerformed(evt);
            }
        });
        menuAdmin.add(item_encerrar_votacao);

        item_apresentar_resultado.setText("apresentar resultado");
        item_apresentar_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_apresentar_resultadoActionPerformed(evt);
            }
        });
        menuAdmin.add(item_apresentar_resultado);

        menuBar.add(menuAdmin);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_admin_apresentar_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel_sistema_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(253, 253, 253)
                    .addComponent(painel_admin_encerrar_votacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(786, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(529, 529, 529)
                    .addComponent(painel_admin_iniciar_votacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(510, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(529, 529, 529)
                    .addComponent(painel_eleitor_votar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(510, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(529, 529, 529)
                    .addComponent(painel_eleitor_votar_antecipadamente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(510, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(529, 529, 529)
                    .addComponent(painel_sistema_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(510, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_sistema_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 645, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_admin_apresentar_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(361, 361, 361)
                    .addComponent(painel_admin_encerrar_votacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(284, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(544, 544, 544)
                    .addComponent(painel_admin_iniciar_votacao, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addGap(545, 545, 545)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(382, 382, 382)
                    .addComponent(painel_eleitor_votar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(382, 382, 382)
                    .addComponent(painel_eleitor_votar_antecipadamente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(558, 558, 558)
                    .addComponent(painel_sistema_login, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                    .addGap(559, 559, 559)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void item_votarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_votarActionPerformed
enablePanel("votar");
  }//GEN-LAST:event_item_votarActionPerformed

  private void item_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_logoutActionPerformed
enablePanel("logout");
  }//GEN-LAST:event_item_logoutActionPerformed

  private void item_votar_antecipadamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_votar_antecipadamenteActionPerformed
enablePanel("votar_antecipadamente");
  }//GEN-LAST:event_item_votar_antecipadamenteActionPerformed

  private void item_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_loginActionPerformed
enablePanel("login");
  }//GEN-LAST:event_item_loginActionPerformed

  private void item_iniciar_votacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_iniciar_votacaoActionPerformed
enablePanel("iniciar_votacao");
  }//GEN-LAST:event_item_iniciar_votacaoActionPerformed

  private void item_encerrar_votacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_encerrar_votacaoActionPerformed
enablePanel("encerrar_votacao");
  }//GEN-LAST:event_item_encerrar_votacaoActionPerformed

  private void item_apresentar_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_apresentar_resultadoActionPerformed
enablePanel("apresentar_resultado");
  }//GEN-LAST:event_item_apresentar_resultadoActionPerformed

    private void butao_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao_loginActionPerformed
            // TODO add your handling code here:
        if(cidadaoActivo.verificaCC_password((Integer.parseInt(field_cc.getText())), field_password.getText())){
            enablePanel("logout");
            enablePanel("votar");
        }
        else System.out.println("Tente Novamente!");
        
        if(cidadaoActivo.podeVotarAntecipadamente()){
            enablePanel("votar_antecipadamente");
        }
        
        if(cidadaoActivo.verificaPermissoesAdmin()){
            enablePanel("iniciar_votacao");
            enablePanel("encerrar_votacao");
            enablePanel("apresentar_resultado");
        }
        
    }//GEN-LAST:event_butao_loginActionPerformed

    private void field_ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_ccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_ccActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainWindow().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butao_login;
    private javax.swing.JTextField field_cc;
    private javax.swing.JTextField field_password;
    private javax.swing.JMenuItem item_apresentar_resultado;
    private javax.swing.JMenuItem item_encerrar_votacao;
    private javax.swing.JMenuItem item_iniciar_votacao;
    private javax.swing.JMenuItem item_login;
    private javax.swing.JMenuItem item_logout;
    private javax.swing.JMenuItem item_votar;
    private javax.swing.JMenuItem item_votar_antecipadamente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEleitor;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JPanel painel_admin_apresentar_resultado;
    private javax.swing.JPanel painel_admin_encerrar_votacao;
    private javax.swing.JPanel painel_admin_iniciar_votacao;
    private javax.swing.JPanel painel_eleitor_votar;
    private javax.swing.JPanel painel_eleitor_votar_antecipadamente;
    private javax.swing.JPanel painel_sistema_login;
    private javax.swing.JPanel painel_sistema_logout;
    // End of variables declaration//GEN-END:variables
}
